import { Given, When, Then } from "@badeball/cypress-cucumber-preprocessor";
import { signupPage } from "../../../pages/SignupPage";
import { paymentPage } from "../../../pages/PaymentPage";
import { headerPage } from "../../../pages/HeaderPage";
import { deletionPage } from "../../../pages/DeletionPage";
import { DataGenerator } from "../../../utils/DataGenerator";

// Global variable to store the generated user data for subsequent steps
let currentUser;

// --- STEP 1: Initiate Signup with Random Data ---
When("ich einen neuen Benutzer mit zufälligen Daten registriere", () => {
    // 1. Generate random user data using Faker
    currentUser = DataGenerator.getUser();
    
    // 2. Log data for debugging purposes
    cy.log(`Creating User: ${currentUser.userName} | ${currentUser.email}`);

    // 3. Perform initial signup action
    signupPage.initiateSignup(currentUser.userName, currentUser.email);
});

// --- STEP 2: Fill Detailed Registration Form ---
When("ich das Formular mit {string} ausfülle und abschicke", (ignoredPassword) => {
    // We ignore the static password from the feature file 
    // and use the fresh data generated by DataGenerator.
    signupPage.fillForm(currentUser);
});



// --- STEP 4: Handle Button Clicks (Common Actions) ---
When("ich auf den {string} Button klicke", (btnText) => {
    switch (btnText) {
        case "Download Invoice":
            paymentPage.clickDownloadInvoice();
            break;
            
        case "Continue":
            // Check body to find the visible continue button dynamically
            cy.get('body').then(($body) => {
                if ($body.find('[data-qa="continue-button"]').length > 0) {
                     cy.get('[data-qa="continue-button"]').click();
                }
            });
            break;
            
        case "Delete Account":
            headerPage.clickDeleteAccount();
            break;
            
        default:
            throw new Error(`Button definition not found: ${btnText}`);
    }
});

// --- STEP 5: Validate Account Deletion ---
Then("sollte die Löschbestätigung {string} sichtbar sein", (message) => {
    deletionPage.verifyAccountDeleted();
    deletionPage.successMessage.should('contain.text', message);
});